AUG:
  MEAN:
  - 0.4712
  - 0.4499
  - 0.4031
  STD:
  - 0.2726
  - 0.2634
  - 0.2794
  TEST_CROP: true
DATA:
  IMG_SIZE: 84
  NUM_WORKERS: 8
  VALID:
    BATCH_SIZE: 8
    DATASET_NAMES:
    - miniImageNet
    DATASET_ROOTS:
    - path-to-miniImageNet
    EPISODE_DESCR_CONFIG:
      MAX_NUM_QUERY: 15
      MIN_EXAMPLES_IN_CLASS: 20
      NUM_QUERY: 15
      NUM_SUPPORT: 5
      NUM_TASKS_PER_EPOCH: 50
      NUM_WAYS: 5
      SEQUENTIAL_SAMPLING: 0
      USE_DAG_HIERARCHY: false
GPU_ID: 2
IS_TRAIN: 0
MODEL:
  BACKBONE: resnet12
  CLASSIFIER: finetune
  CLASSIFIER_PARAMETERS:
  - 100
  - 100
  - null
  - null
  - null
  - false
  - false
  - fc
  NAME: evaluation
  PRETRAINED: ./pn-mini.pth
  TYPE: fewshot_finetune
OUTPUT: ./new_metadataset_result/
SEARCH_HYPERPARAMETERS:
  EPOCH_RANGE:
  - 10
  - 20
  - 30
  LR_BACKBONE_RANGE:
  - 0.01
  - 0.05
  - 0.25
  LR_HEAD_RANGE:
  - 0.02
  - 0.1
  - 0.5
